name: Tests

on: 
  push:
  pull_request:
    types: [opened]

jobs:
  Tests:
    runs-on: macos-15-xlarge
    steps:
    - name: Cancel previous jobs
      uses: styfle/cancel-workflow-action@0.11.0

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Load Latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build project
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -destination 'name=iPhone 16 Pro,OS=18.0' -scheme 'PovioKitAuth-Package' | xcpretty

    - name: Run tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -destination 'name=iPhone 16 Pro,OS=18.0' -scheme 'PovioKitAuth-Package' | xcpretty

